In [1]:
import pandas as pd

In [2]:
data= pd.read_csv('retail_store_sales.csv')

In [3]:
data.head(4)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN

In [4]:
data.sample(5)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
7441,TXN_4070576,CUST_18,Computers and electric accessories,Item_9_CEA,17.0,6.0,102.0,Credit Card,In-store,2022-03-19,True
3690,TXN_2219704,CUST_25,Electric household essentials,Item_6_EHE,12.5,6.0,75.0,Cash,Online,2024-10-24,NaN
297,TXN_5944361,CUST_01,Milk Products,Item_19_MILK,32.0,4.0,128.0,Credit Card,In-store,2022-10-10,False
10212,TXN_9217819,CUST_16,Furniture,Item_2_FUR,6.5,8.0,52.0,Digital Wallet,In-store,2022-11-04,NaN
8588,TXN_6968704,CUST_09,Furniture,Item_22_FUR,36.5,4.0,146.0,Credit Card,In-store,2024-12-20,False

In [5]:
len(data)

12575

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.9+ MB

In [7]:
data.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
data.columns=data.columns.str.lower()

In [9]:
data.columns=data.columns.str.replace(" " ,'_')

In [10]:
data['category'].unique()

<ArrowStringArray>
[                        'Patisserie',                      'Milk Products',
                           'Butchers',                          'Beverages',
                               'Food',                          'Furniture',
      'Electric household essentials', 'Computers and electric accessories']
Length: 8, dtype: str

In [11]:
(data['item'].isnull().sum()/ len(data))*100

np.float64(9.646123260437376)

## 2. Understanding the Missing Value Pattern
Four columns can be missing: Item, Price Per Unit, Quantity, Total Spent. Rather than treating each column's missingness independently, we check which columns tend to be missing together in the same row — this reveals what's actually recoverable.

In [12]:
cols = ['item','price_per_unit','quantity','total_spent','discount_applied']
data['pattern']=data[cols].apply(lambda r: tuple(c for c in cols if pd.isna(r[c])), axis=1)

In [13]:
data['pattern'].value_counts()

pattern
()                                                 7579
(discount_applied,)                                3783
(item, price_per_unit)                              404
(item, quantity, total_spent)                       393
(item, quantity, total_spent, discount_applied)     211
(item, price_per_unit, discount_applied)            205
Name: count, dtype: int64

In [14]:
data['quantity'].mode()

0    10.0
Name: quantity, dtype: float64

In [15]:
data.drop(columns=['pattern'],inplace=True)

## 3. Verifying the Static Price Property
The dataset description claims each item has a fixed price. Before relying on that, we verify it directly, and also check whether price alone is enough to identify an item, or whether we need Category too.

In [16]:
known = data.dropna(subset=['item', 'price_per_unit'])
known

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [17]:
# Does each item map to exactly one price?
item_price = known.groupby('item')['price_per_unit'].nunique()
print("Items with more than one price:", (item_price > 1).sum(), "out of", item_price.shape[0])

Items with more than one price: 0 out of 200

In [18]:
known['discount_applied'].mode()

0    True
Name: discount_applied, dtype: object

In [19]:
known.groupby('price_per_unit')['discount_applied']

In [20]:
cols = [
    "item", "price_per_unit",
    "quantity", "total_spent","discount_applied"
]

print(data[cols].isnull().sum())
print(data[cols].isnull().value_counts())

item                1213
price_per_unit       609
quantity             604
total_spent          604
discount_applied    4199
dtype: int64
item   price_per_unit  quantity  total_spent  discount_applied
False  False           False     False        False               7579
                                              True                3783
True   True            False     False        False                404
       False           True      True         False                393
                                              True                 211
       True            False     False        True                 205
Name: count, dtype: int64

In [21]:
df=data.copy()

In [22]:
price_to_item = (
    df.dropna(subset=["item", "price_per_unit"])
      .drop_duplicates(subset=["price_per_unit"])
      .set_index("price_per_unit")["item"]
)

In [23]:
price_to_item

price_per_unit
18.5     Item_10_PAT
29.0    Item_17_MILK
21.5     Item_12_BUT
27.5     Item_16_BEV
12.5     Item_6_FOOD
5.0      Item_1_FOOD
36.5     Item_22_BUT
8.0       Item_3_BUT
6.5      Item_2_FOOD
39.5     Item_24_PAT
23.0     Item_13_EHE
14.0      Item_7_BEV
9.5       Item_4_EHE
24.5     Item_14_FUR
33.5     Item_20_BUT
41.0     Item_25_FUR
20.0    Item_11_FOOD
35.0     Item_21_EHE
38.0    Item_23_FOOD
15.5      Item_8_BEV
11.0      Item_5_CEA
32.0    Item_19_MILK
26.0     Item_15_CEA
30.5    Item_18_FOOD
17.0     Item_9_FOOD
Name: item, dtype: str

In [24]:
price_to_item[27.5]

'Item_16_BEV'

In [25]:
missing_item_mask = df["item"].isna()

In [26]:
df.loc[missing_item_mask, "item"] = (
    df.loc[missing_item_mask, "price_per_unit"]
      .map(price_to_item)
)

In [27]:
print("Missing items after filling:", df["item"].isna().sum())

Missing items after filling: 609

In [28]:
print("Remaining missing items:")
print(df[df["item"].isna()][["item", "price_per_unit"]])

# Check missing values in all columns
print(df.isnull().sum())

Remaining missing items:
      item  price_per_unit
5      NaN             NaN
11     NaN             NaN
17     NaN             NaN
21     NaN             NaN
32     NaN             NaN
...    ...             ...
12435  NaN             NaN
12457  NaN             NaN
12477  NaN             NaN
12491  NaN             NaN
12511  NaN             NaN

[609 rows x 2 columns]
transaction_id         0
customer_id            0
category               0
item                 609
price_per_unit       609
quantity             604
total_spent          604
payment_method         0
location               0
transaction_date       0
discount_applied    4199
dtype: int64

In [29]:
data[data['item'].isna()]

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
...,...,...,...,...,...,...,...,...,...,...,...
12527,TXN_1069238,CUST_23,Food,NaN,5.0,NaN,NaN,Digital Wallet,In-store,2022-08-13,False
12552,TXN_4823896,CUST_05,Milk Products,NaN,8.0,NaN,NaN,Cash,In-store,2022-07-21,False
12556,TXN_4397672,CUST_04,Beverages,NaN,41.0,NaN,NaN,Credit Card,Online,2024-11-28,True
12562,TXN_7422454,CUST_07,Butchers,NaN,33.5,NaN,NaN,Cash,Online,2023-04-15,NaN
12564,TXN_2153066,CUST_17,Electric household essentials,NaN,29.0,NaN,NaN,Digital Wallet,In-store,2024-03-28,False

In [30]:
df.loc[df['transaction_id']=='TXN_1372952']

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
7,TXN_1372952,CUST_21,Furniture,Item_20_BUT,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True

In [31]:
df['item'].nunique()

200

In [32]:
df.isnull().sum()

transaction_id         0
customer_id            0
category               0
item                 609
price_per_unit       609
quantity             604
total_spent          604
payment_method         0
location               0
transaction_date       0
discount_applied    4199
dtype: int64

In [33]:
clean_data= df.copy()

In [34]:
cols = ['item','price_per_unit','quantity','total_spent']
df['pattern']=df[cols].apply(lambda r: tuple(c for c in cols if pd.isna(r[c])), axis=1)

In [35]:
df['pattern'].value_counts()

pattern
()                         11362
(item, price_per_unit)       609
(quantity, total_spent)      604
Name: count, dtype: int64

In [36]:
cols=['quantity','price_per_unit']
df['price_quantity']=df[cols].apply(lambda r: tuple(c for c in cols if pd.isna(r[c])),axis=1)

In [37]:
df['price_quantity'].value_counts()

price_quantity
()                   11362
(price_per_unit,)      609
(quantity,)            604
Name: count, dtype: int64

In [38]:
cols=['total_spent','price_per_unit']
df['price_spent']=df[cols].apply(lambda r: tuple(c for c in cols if pd.isna(r[c])),axis=1)

In [39]:
df['price_spent'].value_counts()

price_spent
()                   11362
(price_per_unit,)      609
(total_spent,)         604
Name: count, dtype: int64

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    12575 non-null  str
 1   customer_id       12575 non-null  str
 2   category          12575 non-null  str
 3   item              11966 non-null  str
 4   price_per_unit    11966 non-null  float64
 5   quantity          11971 non-null  float64
 6   total_spent       11971 non-null  float64
 7   payment_method    12575 non-null  str
 8   location          12575 non-null  str
 9   transaction_date  12575 non-null  str
 10  discount_applied  8376 non-null   object
 11  pattern           12575 non-null  object
 12  price_quantity    12575 non-null  object
 13  price_spent       12575 non-null  object
dtypes: float64(3), object(4), str(7)
memory usage: 2.2+ MB

In [41]:
# 1. Product-level analysis
product_data = clean_data.dropna(
    subset=['item', 'price_per_unit']
)

# 2. Revenue and quantity analysis
sales_data = clean_data.dropna(
    subset=['quantity', 'total_spent']
)

# 3. Discount analysis
discount_data = clean_data.dropna(
    subset=['discount_applied']
)

In [42]:
print("Original rows:", len(data))
print("Product analysis rows:", len(product_data))
print("Sales analysis rows:", len(sales_data))
print("Discount analysis rows:", len(discount_data))

Original rows: 12575
Product analysis rows: 11966
Sales analysis rows: 11971
Discount analysis rows: 8376

In [43]:
print("Total rows:", len(data))

print(
    "Unique transaction IDs:",
    data['transaction_id'].nunique()
)

print(
    "Duplicate transaction IDs:",
    data['transaction_id'].duplicated().sum()
)

Total rows: 12575
Unique transaction IDs: 12575
Duplicate transaction IDs: 0

In [44]:
# 4. Check negative or invalid values
print("Negative quantity:",
      (data['quantity'] < 0).sum())

print("Negative price:",
      (data['price_per_unit'] < 0).sum())

print("Negative total spent:",
      (data['total_spent'] < 0).sum())

Negative quantity: 0
Negative price: 0
Negative total spent: 0

In [45]:
import mysql.connector
from sqlalchemy import create_engine

In [46]:
conn=mysql.connector.connect(
    host='localhost',
    user='root',
    password='292005',
    database='retail_sales'
)

In [47]:
print("Connection successful!" if conn.is_connected() else "Connection failed.")

Connection successful!

In [48]:
engine = create_engine("mysql+pymysql://root:292005@localhost:3306/retail_sales")

In [51]:
clean_data.to_sql(
    name='sales_insights',
    con= engine,
    if_exists='fail',
    index=False
)
print("Dataset successfully transferred to MySQL Workbench!")

Dataset successfully transferred to MySQL Workbench!